name: Ma Premiere CI

on:
  push:
    branches: [ "main" ]

jobs:
  verification:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Le robot installe streamlit et pytest d'un coup grâce au fichier text
      - name: Installer les dependances
        run: pip install -r requirements.txt

      - name: Lancer le test avec pytest
        run: pytest test_calcul.py