name: Ma Premiere CI

on:
  push:
    branches: [ "main" ]

jobs:
  verification:
    runs-on: ubuntu-latest
    
    # 🔥 C'EST ICI QUE LA MAGIE OPÈRE 🔥
    strategy:
      matrix:
        version-python: ['3.9', '3.10', '3.11']

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Python ${{ matrix.version-python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version-python }} # Le robot prend dynamiquement la version

      - name: Installer les dependances
        run: pip install -r requirements.txt

      - name: Lancer le test avec pytest
        run: pytest test_calcul.py